USE [master]
GO

/****** Object:  Database [QuanLySinhVien]    Script Date: 10/1/2022 2:40:53 PM ******/
CREATE DATABASE [QuanLySinhVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLySinhVien', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuanLySinhVien.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLySinhVien_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuanLySinhVien_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLySinhVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLySinhVien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLySinhVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLySinhVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QuanLySinhVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLySinhVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QuanLySinhVien] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLySinhVien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLySinhVien] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLySinhVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLySinhVien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLySinhVien] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLySinhVien] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLySinhVien] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLySinhVien] SET  READ_WRITE 
GO


